### ISSUE TITLE
Crashes Beat Saber on Start

### ISSUE THREAD

**Issue by 200Tigersbloxed** [ToniMacaroni/SaberFactoryLegacy#1]
Hey first congrats on the cool mod, was looking forward to using it, but it seems it's crashing me on start. Whenever I start Beat Saber, it will go to the Black Scrren, and about 5-10 seconds after, the UnityCrashHelper will open and then Beat Saber closes.

Here's the log file:
[2020.06.14.20.05.21.log](https://github.com/ToniMacaroni/SaberFactory/files/4777566/2020.06.14.20.05.21.log)

Thanks a lot!

**Comment by AsoDesu** [comment]
What version of the game are you using?
Also I recommend joining the SaberFactory discord server, (link in the README) and asking in there, or you could ask people in the BSMG discord. Then your issue would be resolved sooner.

**Comment by 200Tigersbloxed** [comment]
I'm on v1.10.0, the latest version of Beat Saber. I'll try joining the discord to see if I can get any more help, thanks!
